---
pg_version: "14"
pg_conf_dir: "/etc/postgresql/{{ pg_version }}/main"
pg_listen_addresses: "localhost"
pg_shared_buffers: "512MB"
pg_work_mem: "16MB"
db_name: "app_db"
db_user: "app_user"
db_password: ""
db_seed_table: "contacts"
