---
- name: Install packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - curl
      - vim
      - htop
      - postgresql-client
      - mysql-client
      - git
      - chrony
      - tzdata
      - python3-psycopg2
      - awscli
    state: present

- name: Set timezone to Asia/Jakarta
  become: true
  community.general.timezone:
    name: Asia/Jakarta

- name: Deploy chrony.conf template
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: restart chronyd

- name: Ensure chronyd is started and enabled
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true

- name: Deploy logrotate config
  ansible.builtin.copy:
    src: linux-ops.logrotate
    dest: /etc/logrotate.d/linux-ops
    owner: root
    group: root
    mode: "0644"

- name: Deploy log-rotation script
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../scripts/maintenance/log-rotation.sh"
    dest: /usr/local/bin/log-rotation.sh
    owner: root
    group: root
    mode: "0755"

- name: Deploy status-check script
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../scripts/maintenance/status-check.sh"
    dest: /usr/local/bin/status-check.sh
    owner: root
    group: root
    mode: "0755"
