plugin: amazon.aws.aws_ec2
regions:
  - ap-southeast-3
filters:
  tag:Name: linux-ops
compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: /Users/admin/.ssh/awslinux
