---
- name: Setup backup scripts on EC2
  hosts: all
  become: true
  vars:
    backup_bucket: "{{ lookup('env', 'BACKUP_BUCKET') | default('linux-ops-bucket', true) }}"
  roles:
    - role: common
    - role: backup
