---
backup_dir: /var/backups
backup_install_path: /opt/backup/scripts
backup_bucket: "{{ sops_backup_bucket | default(lookup('env', 'BACKUP_BUCKET') | default('', true), true) }}"
backup_retention_days: 7
backup_enable_cron: true
backup_cron_hour: "2"
backup_cron_minute: "0"
backup_db_name: "{{ sops_db_name | default(db_name | default('app_db'), true) }}"
backup_db_user: "{{ sops_db_user | default('postgres') }}"
backup_db_password: "{{ sops_db_password | default(db_password | default(''), true) }}"
backup_aws_access_key: "{{ sops_aws_access_key | default('') }}"
backup_aws_secret_key: "{{ sops_aws_secret_key | default('') }}"
backup_aws_region: "{{ sops_aws_region | default('ap-southeast-3') }}"
